"""empty message

Revision ID: 68c9dcaaf6b4
Revises: f720104f8db5
Create Date: 2026-04-30 20:42:24.167669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c9dcaaf6b4'
down_revision = 'f720104f8db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.drop_column('relatorio')

    # ### end Alembic commands ###
