"""empty message

Revision ID: d7289d9d52af
Revises: c658a632115d
Create Date: 2026-04-26 22:18:07.881591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7289d9d52af'
down_revision = 'c658a632115d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
